# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObsidianServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadVideo = channel.unary_unary(
                '/obsidian.ObsidianService/UploadVideo',
                request_serializer=service__pb2.UploadRequest.SerializeToString,
                response_deserializer=service__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/obsidian.ObsidianService/Chat',
                request_serializer=service__pb2.ChatRequest.SerializeToString,
                response_deserializer=service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/obsidian.ObsidianService/GetHistory',
                request_serializer=service__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=service__pb2.GetHistoryResponse.FromString,
                _registered_method=True)


class ObsidianServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadVideo(self, request, context):
        """Uploads a video for processing. Returns the video ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Sends a chat message and receives a streaming response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Retrieves chat history.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObsidianServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadVideo,
                    request_deserializer=service__pb2.UploadRequest.FromString,
                    response_serializer=service__pb2.UploadResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=service__pb2.ChatRequest.FromString,
                    response_serializer=service__pb2.ChatResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=service__pb2.GetHistoryRequest.FromString,
                    response_serializer=service__pb2.GetHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'obsidian.ObsidianService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('obsidian.ObsidianService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObsidianService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.ObsidianService/UploadVideo',
            service__pb2.UploadRequest.SerializeToString,
            service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/obsidian.ObsidianService/Chat',
            service__pb2.ChatRequest.SerializeToString,
            service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/obsidian.ObsidianService/GetHistory',
            service__pb2.GetHistoryRequest.SerializeToString,
            service__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
