/**
 * @fileoverview gRPC-Web generated client stub for obsidian
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as service_pb from './service_pb'; // proto import: "service.proto"


export class ObsidianServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadVideo = new grpcWeb.MethodDescriptor(
    '/obsidian.ObsidianService/UploadVideo',
    grpcWeb.MethodType.UNARY,
    service_pb.UploadRequest,
    service_pb.UploadResponse,
    (request: service_pb.UploadRequest) => {
      return request.serializeBinary();
    },
    service_pb.UploadResponse.deserializeBinary
  );

  uploadVideo(
    request: service_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.UploadResponse>;

  uploadVideo(
    request: service_pb.UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.UploadResponse) => void): grpcWeb.ClientReadableStream<service_pb.UploadResponse>;

  uploadVideo(
    request: service_pb.UploadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.UploadResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/obsidian.ObsidianService/UploadVideo',
        request,
        metadata || {},
        this.methodDescriptorUploadVideo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/obsidian.ObsidianService/UploadVideo',
    request,
    metadata || {},
    this.methodDescriptorUploadVideo);
  }

  methodDescriptorChat = new grpcWeb.MethodDescriptor(
    '/obsidian.ObsidianService/Chat',
    grpcWeb.MethodType.SERVER_STREAMING,
    service_pb.ChatRequest,
    service_pb.ChatResponse,
    (request: service_pb.ChatRequest) => {
      return request.serializeBinary();
    },
    service_pb.ChatResponse.deserializeBinary
  );

  chat(
    request: service_pb.ChatRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<service_pb.ChatResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/obsidian.ObsidianService/Chat',
      request,
      metadata || {},
      this.methodDescriptorChat);
  }

  methodDescriptorGetHistory = new grpcWeb.MethodDescriptor(
    '/obsidian.ObsidianService/GetHistory',
    grpcWeb.MethodType.UNARY,
    service_pb.GetHistoryRequest,
    service_pb.GetHistoryResponse,
    (request: service_pb.GetHistoryRequest) => {
      return request.serializeBinary();
    },
    service_pb.GetHistoryResponse.deserializeBinary
  );

  getHistory(
    request: service_pb.GetHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.GetHistoryResponse>;

  getHistory(
    request: service_pb.GetHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.GetHistoryResponse) => void): grpcWeb.ClientReadableStream<service_pb.GetHistoryResponse>;

  getHistory(
    request: service_pb.GetHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.GetHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/obsidian.ObsidianService/GetHistory',
        request,
        metadata || {},
        this.methodDescriptorGetHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/obsidian.ObsidianService/GetHistory',
    request,
    metadata || {},
    this.methodDescriptorGetHistory);
  }

  methodDescriptorListVideos = new grpcWeb.MethodDescriptor(
    '/obsidian.ObsidianService/ListVideos',
    grpcWeb.MethodType.UNARY,
    service_pb.ListVideosRequest,
    service_pb.ListVideosResponse,
    (request: service_pb.ListVideosRequest) => {
      return request.serializeBinary();
    },
    service_pb.ListVideosResponse.deserializeBinary
  );

  listVideos(
    request: service_pb.ListVideosRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.ListVideosResponse>;

  listVideos(
    request: service_pb.ListVideosRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.ListVideosResponse) => void): grpcWeb.ClientReadableStream<service_pb.ListVideosResponse>;

  listVideos(
    request: service_pb.ListVideosRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.ListVideosResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/obsidian.ObsidianService/ListVideos',
        request,
        metadata || {},
        this.methodDescriptorListVideos,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/obsidian.ObsidianService/ListVideos',
    request,
    metadata || {},
    this.methodDescriptorListVideos);
  }

  methodDescriptorClearHistory = new grpcWeb.MethodDescriptor(
    '/obsidian.ObsidianService/ClearHistory',
    grpcWeb.MethodType.UNARY,
    service_pb.ClearHistoryRequest,
    service_pb.ClearHistoryResponse,
    (request: service_pb.ClearHistoryRequest) => {
      return request.serializeBinary();
    },
    service_pb.ClearHistoryResponse.deserializeBinary
  );

  clearHistory(
    request: service_pb.ClearHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<service_pb.ClearHistoryResponse>;

  clearHistory(
    request: service_pb.ClearHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: service_pb.ClearHistoryResponse) => void): grpcWeb.ClientReadableStream<service_pb.ClearHistoryResponse>;

  clearHistory(
    request: service_pb.ClearHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: service_pb.ClearHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/obsidian.ObsidianService/ClearHistory',
        request,
        metadata || {},
        this.methodDescriptorClearHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/obsidian.ObsidianService/ClearHistory',
    request,
    metadata || {},
    this.methodDescriptorClearHistory);
  }

}

