/**
 * @fileoverview gRPC-Web generated client stub for obsidian
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.obsidian = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.obsidian.ObsidianServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.obsidian.ObsidianServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.UploadRequest,
 *   !proto.obsidian.UploadResponse>}
 */
const methodDescriptor_ObsidianService_UploadVideo = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/UploadVideo',
  grpc.web.MethodType.UNARY,
  proto.obsidian.UploadRequest,
  proto.obsidian.UploadResponse,
  /**
   * @param {!proto.obsidian.UploadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.obsidian.UploadResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.UploadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.UploadResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.UploadResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.uploadVideo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_UploadVideo,
      callback);
};


/**
 * @param {!proto.obsidian.UploadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.UploadResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.uploadVideo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_UploadVideo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.ChatRequest,
 *   !proto.obsidian.ChatResponse>}
 */
const methodDescriptor_ObsidianService_Chat = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/Chat',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.obsidian.ChatRequest,
  proto.obsidian.ChatResponse,
  /**
   * @param {!proto.obsidian.ChatRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.obsidian.ChatResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.ChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ChatResponse>}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.chat =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/obsidian.ObsidianService/Chat',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_Chat);
};


/**
 * @param {!proto.obsidian.ChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ChatResponse>}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.chat =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/obsidian.ObsidianService/Chat',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_Chat);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.GetHistoryRequest,
 *   !proto.obsidian.GetHistoryResponse>}
 */
const methodDescriptor_ObsidianService_GetHistory = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/GetHistory',
  grpc.web.MethodType.UNARY,
  proto.obsidian.GetHistoryRequest,
  proto.obsidian.GetHistoryResponse,
  /**
   * @param {!proto.obsidian.GetHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.obsidian.GetHistoryResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.GetHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.GetHistoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.GetHistoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.getHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/GetHistory',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetHistory,
      callback);
};


/**
 * @param {!proto.obsidian.GetHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.GetHistoryResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.getHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/GetHistory',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetHistory);
};


module.exports = proto.obsidian;

