/**
 * @fileoverview gRPC-Web generated client stub for obsidian
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

let messages = require('./service_pb.js');

// Determine global scope safely
const globalScope = typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : (typeof global !== 'undefined' ? global : null));

// Fallback logic: If require didn't give us named exports, check the global 'proto.obsidian'
if ((!messages || !messages.UploadRequest || !messages.GetStatusRequest) && globalScope && globalScope.proto && globalScope.proto.obsidian) {
  console.log("GRPC-WEB: Falling back to global proto.obsidian for messages");
  messages = globalScope.proto.obsidian;
}

if (!messages.GetStatusRequest) {
  console.warn("GRPC-WEB: GetStatusRequest MISSING from messages!", Object.keys(messages));
  if (globalScope && globalScope.proto && globalScope.proto.obsidian) {
    console.warn("GRPC-WEB: Global proto keys:", Object.keys(globalScope.proto.obsidian));
  }
}

// Local proto object for constructing the service client export
const proto = {};
proto.obsidian = {};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.obsidian.ObsidianServiceClient =
  function (hostname, credentials, options) {
    if (!options) options = {};
    options.format = 'text';

    /**
     * @private @const {!grpc.web.GrpcWebClientBase} The client
     */
    this.client_ = new grpc.web.GrpcWebClientBase(options);

    /**
     * @private @const {string} The hostname
     */
    this.hostname_ = hostname.replace(/\/+$/, '');

  };


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.obsidian.ObsidianServicePromiseClient =
  function (hostname, credentials, options) {
    if (!options) options = {};
    options.format = 'text';

    /**
     * @private @const {!grpc.web.GrpcWebClientBase} The client
     */
    this.client_ = new grpc.web.GrpcWebClientBase(options);

    /**
     * @private @const {string} The hostname
     */
    this.hostname_ = hostname.replace(/\/+$/, '');

  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.UploadRequest,
 *   !proto.obsidian.UploadResponse>}
 */
const methodDescriptor_ObsidianService_UploadVideo = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/UploadVideo',
  grpc.web.MethodType.UNARY,
  messages.UploadRequest,
  messages.UploadResponse,
  /**
   * @param {!proto.obsidian.UploadRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.UploadResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.UploadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.UploadResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.UploadResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.uploadVideo =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_UploadVideo,
      callback);
  };


/**
 * @param {!proto.obsidian.UploadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.UploadResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.uploadVideo =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_UploadVideo);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.CreateSessionRequest,
 *   !proto.obsidian.CreateSessionResponse>}
 */
const methodDescriptor_ObsidianService_CreateSession = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/CreateSession',
  grpc.web.MethodType.UNARY,
  messages.CreateSessionRequest,
  messages.CreateSessionResponse,
  /**
   * @param {!proto.obsidian.CreateSessionRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.CreateSessionResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.CreateSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.CreateSessionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.CreateSessionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.createSession =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/CreateSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_CreateSession,
      callback);
  };


/**
 * @param {!proto.obsidian.CreateSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.CreateSessionResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.createSession =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/CreateSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_CreateSession);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.ChatRequest,
 *   !proto.obsidian.ChatResponse>}
 */
const methodDescriptor_ObsidianService_Chat = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/Chat',
  grpc.web.MethodType.SERVER_STREAMING,
  messages.ChatRequest,
  messages.ChatResponse,
  /**
   * @param {!proto.obsidian.ChatRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.ChatResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.ChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ChatResponse>}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.chat =
  function (request, metadata) {
    return this.client_.serverStreaming(this.hostname_ +
      '/obsidian.ObsidianService/Chat',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_Chat);
  };


/**
 * @param {!proto.obsidian.ChatRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ChatResponse>}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.chat =
  function (request, metadata) {
    return this.client_.serverStreaming(this.hostname_ +
      '/obsidian.ObsidianService/Chat',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_Chat);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.GetHistoryRequest,
 *   !proto.obsidian.GetHistoryResponse>}
 */
const methodDescriptor_ObsidianService_GetHistory = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/GetHistory',
  grpc.web.MethodType.UNARY,
  messages.GetHistoryRequest,
  messages.GetHistoryResponse,
  /**
   * @param {!proto.obsidian.GetHistoryRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.GetHistoryResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.GetHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.GetHistoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.GetHistoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.getHistory =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/GetHistory',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetHistory,
      callback);
  };


/**
 * @param {!proto.obsidian.GetHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.GetHistoryResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.getHistory =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/GetHistory',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetHistory);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.ListSessionsRequest,
 *   !proto.obsidian.ListSessionsResponse>}
 */
const methodDescriptor_ObsidianService_ListSessions = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/ListSessions',
  grpc.web.MethodType.UNARY,
  messages.ListSessionsRequest,
  messages.ListSessionsResponse,
  /**
   * @param {!proto.obsidian.ListSessionsRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.ListSessionsResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.ListSessionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.ListSessionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ListSessionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.listSessions =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/ListSessions',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_ListSessions,
      callback);
  };


/**
 * @param {!proto.obsidian.ListSessionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.ListSessionsResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.listSessions =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/ListSessions',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_ListSessions);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.ListVideosRequest,
 *   !proto.obsidian.ListVideosResponse>}
 */
const methodDescriptor_ObsidianService_ListVideos = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/ListVideos',
  grpc.web.MethodType.UNARY,
  messages.ListVideosRequest,
  messages.ListVideosResponse,
  /**
   * @param {!proto.obsidian.ListVideosRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.ListVideosResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.ListVideosRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.ListVideosResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.ListVideosResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.listVideos =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/ListVideos',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_ListVideos,
      callback);
  };


/**
 * @param {!proto.obsidian.ListVideosRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.ListVideosResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.listVideos =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/ListVideos',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_ListVideos);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.DeleteSessionRequest,
 *   !proto.obsidian.DeleteSessionResponse>}
 */
const methodDescriptor_ObsidianService_DeleteSession = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/DeleteSession',
  grpc.web.MethodType.UNARY,
  messages.DeleteSessionRequest,
  messages.DeleteSessionResponse,
  /**
   * @param {!proto.obsidian.DeleteSessionRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.DeleteSessionResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.DeleteSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.DeleteSessionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.DeleteSessionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.deleteSession =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/DeleteSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_DeleteSession,
      callback);
  };


/**
 * @param {!proto.obsidian.DeleteSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.DeleteSessionResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.deleteSession =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/DeleteSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_DeleteSession);
  };


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.RenameSessionRequest,
 *   !proto.obsidian.RenameSessionResponse>}
 */
const methodDescriptor_ObsidianService_RenameSession = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/RenameSession',
  grpc.web.MethodType.UNARY,
  messages.RenameSessionRequest,
  messages.RenameSessionResponse,
  /**
   * @param {!proto.obsidian.RenameSessionRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.RenameSessionResponse.deserializeBinary
);


/**
 * @param {!proto.obsidian.RenameSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.RenameSessionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.RenameSessionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.renameSession =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/RenameSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_RenameSession,
      callback);
  };


/**
 * @param {!proto.obsidian.RenameSessionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.RenameSessionResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.renameSession =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/RenameSession',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_RenameSession);
  };



/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.obsidian.GetStatusRequest,
 *   !proto.obsidian.GetStatusResponse>}
 */
const methodDescriptor_ObsidianService_GetStatus = new grpc.web.MethodDescriptor(
  '/obsidian.ObsidianService/GetStatus',
  grpc.web.MethodType.UNARY,
  messages.GetStatusRequest,
  messages.GetStatusResponse,
  /**
   * @param {!proto.obsidian.GetStatusRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  messages.GetStatusResponse.deserializeBinary
);

/**
 * @param {!proto.obsidian.GetStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.obsidian.GetStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.obsidian.GetStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.obsidian.ObsidianServiceClient.prototype.getStatus =
  function (request, metadata, callback) {
    return this.client_.rpcCall(this.hostname_ +
      '/obsidian.ObsidianService/GetStatus',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetStatus,
      callback);
  };

/**
 * @param {!proto.obsidian.GetStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.obsidian.GetStatusResponse>}
 *     Promise that resolves to the response
 */
proto.obsidian.ObsidianServicePromiseClient.prototype.getStatus =
  function (request, metadata) {
    return this.client_.unaryCall(this.hostname_ +
      '/obsidian.ObsidianService/GetStatus',
      request,
      metadata || {},
      methodDescriptor_ObsidianService_GetStatus);
  };

module.exports = proto.obsidian;
