/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: service.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace obsidian {
    export class UploadRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            file_path?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("file_path" in data && data.file_path != undefined) {
                    this.file_path = data.file_path;
                }
            }
        }
        get file_path() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set file_path(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            file_path?: string;
        }): UploadRequest {
            const message = new UploadRequest({});
            if (data.file_path != null) {
                message.file_path = data.file_path;
            }
            return message;
        }
        toObject() {
            const data: {
                file_path?: string;
            } = {};
            if (this.file_path != null) {
                data.file_path = this.file_path;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.file_path.length)
                writer.writeString(1, this.file_path);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UploadRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UploadRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.file_path = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UploadRequest {
            return UploadRequest.deserialize(bytes);
        }
    }
    export class UploadResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            video_id?: string;
            status?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("video_id" in data && data.video_id != undefined) {
                    this.video_id = data.video_id;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
            }
        }
        get video_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set video_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            video_id?: string;
            status?: string;
        }): UploadResponse {
            const message = new UploadResponse({});
            if (data.video_id != null) {
                message.video_id = data.video_id;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            return message;
        }
        toObject() {
            const data: {
                video_id?: string;
                status?: string;
            } = {};
            if (this.video_id != null) {
                data.video_id = this.video_id;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.video_id.length)
                writer.writeString(1, this.video_id);
            if (this.status.length)
                writer.writeString(2, this.status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UploadResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UploadResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.video_id = reader.readString();
                        break;
                    case 2:
                        message.status = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UploadResponse {
            return UploadResponse.deserialize(bytes);
        }
    }
    export class ChatRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            video_id?: string;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("video_id" in data && data.video_id != undefined) {
                    this.video_id = data.video_id;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get video_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set video_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            video_id?: string;
            message?: string;
        }): ChatRequest {
            const message = new ChatRequest({});
            if (data.video_id != null) {
                message.video_id = data.video_id;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                video_id?: string;
                message?: string;
            } = {};
            if (this.video_id != null) {
                data.video_id = this.video_id;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.video_id.length)
                writer.writeString(1, this.video_id);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.video_id = reader.readString();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatRequest {
            return ChatRequest.deserialize(bytes);
        }
    }
    export class ChatResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            content?: string;
            type?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
            }
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            content?: string;
            type?: string;
        }): ChatResponse {
            const message = new ChatResponse({});
            if (data.content != null) {
                message.content = data.content;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            return message;
        }
        toObject() {
            const data: {
                content?: string;
                type?: string;
            } = {};
            if (this.content != null) {
                data.content = this.content;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.content.length)
                writer.writeString(1, this.content);
            if (this.type.length)
                writer.writeString(2, this.type);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.content = reader.readString();
                        break;
                    case 2:
                        message.type = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatResponse {
            return ChatResponse.deserialize(bytes);
        }
    }
    export class GetHistoryRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            video_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("video_id" in data && data.video_id != undefined) {
                    this.video_id = data.video_id;
                }
            }
        }
        get video_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set video_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            video_id?: string;
        }): GetHistoryRequest {
            const message = new GetHistoryRequest({});
            if (data.video_id != null) {
                message.video_id = data.video_id;
            }
            return message;
        }
        toObject() {
            const data: {
                video_id?: string;
            } = {};
            if (this.video_id != null) {
                data.video_id = this.video_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.video_id.length)
                writer.writeString(1, this.video_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetHistoryRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetHistoryRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.video_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetHistoryRequest {
            return GetHistoryRequest.deserialize(bytes);
        }
    }
    export class GetHistoryResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            messages?: ChatMessage[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("messages" in data && data.messages != undefined) {
                    this.messages = data.messages;
                }
            }
        }
        get messages() {
            return pb_1.Message.getRepeatedWrapperField(this, ChatMessage, 1) as ChatMessage[];
        }
        set messages(value: ChatMessage[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            messages?: ReturnType<typeof ChatMessage.prototype.toObject>[];
        }): GetHistoryResponse {
            const message = new GetHistoryResponse({});
            if (data.messages != null) {
                message.messages = data.messages.map(item => ChatMessage.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                messages?: ReturnType<typeof ChatMessage.prototype.toObject>[];
            } = {};
            if (this.messages != null) {
                data.messages = this.messages.map((item: ChatMessage) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.messages.length)
                writer.writeRepeatedMessage(1, this.messages, (item: ChatMessage) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetHistoryResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetHistoryResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.messages, () => pb_1.Message.addToRepeatedWrapperField(message, 1, ChatMessage.deserialize(reader), ChatMessage));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetHistoryResponse {
            return GetHistoryResponse.deserialize(bytes);
        }
    }
    export class ChatMessage extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            role?: string;
            content?: string;
            timestamp?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("role" in data && data.role != undefined) {
                    this.role = data.role;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get role() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set role(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set timestamp(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            role?: string;
            content?: string;
            timestamp?: string;
        }): ChatMessage {
            const message = new ChatMessage({});
            if (data.role != null) {
                message.role = data.role;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            return message;
        }
        toObject() {
            const data: {
                role?: string;
                content?: string;
                timestamp?: string;
            } = {};
            if (this.role != null) {
                data.role = this.role;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.role.length)
                writer.writeString(1, this.role);
            if (this.content.length)
                writer.writeString(2, this.content);
            if (this.timestamp.length)
                writer.writeString(3, this.timestamp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.role = reader.readString();
                        break;
                    case 2:
                        message.content = reader.readString();
                        break;
                    case 3:
                        message.timestamp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ChatMessage {
            return ChatMessage.deserialize(bytes);
        }
    }
    export class ListVideosRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): ListVideosRequest {
            const message = new ListVideosRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListVideosRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListVideosRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListVideosRequest {
            return ListVideosRequest.deserialize(bytes);
        }
    }
    export class ListVideosResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            videos?: VideoMetadata[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("videos" in data && data.videos != undefined) {
                    this.videos = data.videos;
                }
            }
        }
        get videos() {
            return pb_1.Message.getRepeatedWrapperField(this, VideoMetadata, 1) as VideoMetadata[];
        }
        set videos(value: VideoMetadata[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            videos?: ReturnType<typeof VideoMetadata.prototype.toObject>[];
        }): ListVideosResponse {
            const message = new ListVideosResponse({});
            if (data.videos != null) {
                message.videos = data.videos.map(item => VideoMetadata.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                videos?: ReturnType<typeof VideoMetadata.prototype.toObject>[];
            } = {};
            if (this.videos != null) {
                data.videos = this.videos.map((item: VideoMetadata) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.videos.length)
                writer.writeRepeatedMessage(1, this.videos, (item: VideoMetadata) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListVideosResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListVideosResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.videos, () => pb_1.Message.addToRepeatedWrapperField(message, 1, VideoMetadata.deserialize(reader), VideoMetadata));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListVideosResponse {
            return ListVideosResponse.deserialize(bytes);
        }
    }
    export class ClearHistoryRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            video_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("video_id" in data && data.video_id != undefined) {
                    this.video_id = data.video_id;
                }
            }
        }
        get video_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set video_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            video_id?: string;
        }): ClearHistoryRequest {
            const message = new ClearHistoryRequest({});
            if (data.video_id != null) {
                message.video_id = data.video_id;
            }
            return message;
        }
        toObject() {
            const data: {
                video_id?: string;
            } = {};
            if (this.video_id != null) {
                data.video_id = this.video_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.video_id.length)
                writer.writeString(1, this.video_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ClearHistoryRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ClearHistoryRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.video_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ClearHistoryRequest {
            return ClearHistoryRequest.deserialize(bytes);
        }
    }
    export class ClearHistoryResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            success?: boolean;
        }): ClearHistoryResponse {
            const message = new ClearHistoryResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ClearHistoryResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ClearHistoryResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ClearHistoryResponse {
            return ClearHistoryResponse.deserialize(bytes);
        }
    }
    export class VideoMetadata extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            path?: string;
            status?: string;
            created_at?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("path" in data && data.path != undefined) {
                    this.path = data.path;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get path() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set path(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set status(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get created_at() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set created_at(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            id?: string;
            path?: string;
            status?: string;
            created_at?: string;
        }): VideoMetadata {
            const message = new VideoMetadata({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.path != null) {
                message.path = data.path;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.created_at != null) {
                message.created_at = data.created_at;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                path?: string;
                status?: string;
                created_at?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.path != null) {
                data.path = this.path;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.path.length)
                writer.writeString(2, this.path);
            if (this.status.length)
                writer.writeString(3, this.status);
            if (this.created_at.length)
                writer.writeString(4, this.created_at);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): VideoMetadata {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new VideoMetadata();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.path = reader.readString();
                        break;
                    case 3:
                        message.status = reader.readString();
                        break;
                    case 4:
                        message.created_at = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): VideoMetadata {
            return VideoMetadata.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedObsidianServiceService {
        static definition = {
            UploadVideo: {
                path: "/obsidian.ObsidianService/UploadVideo",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: UploadRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => UploadRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: UploadResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => UploadResponse.deserialize(new Uint8Array(bytes))
            },
            Chat: {
                path: "/obsidian.ObsidianService/Chat",
                requestStream: false,
                responseStream: true,
                requestSerialize: (message: ChatRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ChatRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ChatResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ChatResponse.deserialize(new Uint8Array(bytes))
            },
            GetHistory: {
                path: "/obsidian.ObsidianService/GetHistory",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetHistoryRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetHistoryRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: GetHistoryResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => GetHistoryResponse.deserialize(new Uint8Array(bytes))
            },
            ListVideos: {
                path: "/obsidian.ObsidianService/ListVideos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ListVideosRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ListVideosRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ListVideosResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ListVideosResponse.deserialize(new Uint8Array(bytes))
            },
            ClearHistory: {
                path: "/obsidian.ObsidianService/ClearHistory",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ClearHistoryRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ClearHistoryRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ClearHistoryResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ClearHistoryResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract UploadVideo(call: grpc_1.ServerUnaryCall<UploadRequest, UploadResponse>, callback: grpc_1.sendUnaryData<UploadResponse>): void;
        abstract Chat(call: grpc_1.ServerWritableStream<ChatRequest, ChatResponse>): void;
        abstract GetHistory(call: grpc_1.ServerUnaryCall<GetHistoryRequest, GetHistoryResponse>, callback: grpc_1.sendUnaryData<GetHistoryResponse>): void;
        abstract ListVideos(call: grpc_1.ServerUnaryCall<ListVideosRequest, ListVideosResponse>, callback: grpc_1.sendUnaryData<ListVideosResponse>): void;
        abstract ClearHistory(call: grpc_1.ServerUnaryCall<ClearHistoryRequest, ClearHistoryResponse>, callback: grpc_1.sendUnaryData<ClearHistoryResponse>): void;
    }
    export class ObsidianServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedObsidianServiceService.definition, "ObsidianService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        UploadVideo: GrpcUnaryServiceInterface<UploadRequest, UploadResponse> = (message: UploadRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<UploadResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<UploadResponse>, callback?: grpc_1.requestCallback<UploadResponse>): grpc_1.ClientUnaryCall => {
            return super.UploadVideo(message, metadata, options, callback);
        };
        Chat: GrpcStreamServiceInterface<ChatRequest, ChatResponse> = (message: ChatRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<ChatResponse> => {
            return super.Chat(message, metadata, options);
        };
        GetHistory: GrpcUnaryServiceInterface<GetHistoryRequest, GetHistoryResponse> = (message: GetHistoryRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<GetHistoryResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<GetHistoryResponse>, callback?: grpc_1.requestCallback<GetHistoryResponse>): grpc_1.ClientUnaryCall => {
            return super.GetHistory(message, metadata, options, callback);
        };
        ListVideos: GrpcUnaryServiceInterface<ListVideosRequest, ListVideosResponse> = (message: ListVideosRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ListVideosResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ListVideosResponse>, callback?: grpc_1.requestCallback<ListVideosResponse>): grpc_1.ClientUnaryCall => {
            return super.ListVideos(message, metadata, options, callback);
        };
        ClearHistory: GrpcUnaryServiceInterface<ClearHistoryRequest, ClearHistoryResponse> = (message: ClearHistoryRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ClearHistoryResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ClearHistoryResponse>, callback?: grpc_1.requestCallback<ClearHistoryResponse>): grpc_1.ClientUnaryCall => {
            return super.ClearHistory(message, metadata, options, callback);
        };
    }
}
