# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08obsidian\"\"\n\rUploadRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"2\n\x0eUploadResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"0\n\x0b\x43hatRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"%\n\x11GetHistoryRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"=\n\x12GetHistoryResponse\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.obsidian.ChatMessage\"?\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\xdb\x01\n\x0fObsidianService\x12\x42\n\x0bUploadVideo\x12\x17.obsidian.UploadRequest\x1a\x18.obsidian.UploadResponse\"\x00\x12\x39\n\x04\x43hat\x12\x15.obsidian.ChatRequest\x1a\x16.obsidian.ChatResponse\"\x00\x30\x01\x12I\n\nGetHistory\x12\x1b.obsidian.GetHistoryRequest\x1a\x1c.obsidian.GetHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=27
  _globals['_UPLOADREQUEST']._serialized_end=61
  _globals['_UPLOADRESPONSE']._serialized_start=63
  _globals['_UPLOADRESPONSE']._serialized_end=113
  _globals['_CHATREQUEST']._serialized_start=115
  _globals['_CHATREQUEST']._serialized_end=163
  _globals['_CHATRESPONSE']._serialized_start=165
  _globals['_CHATRESPONSE']._serialized_end=210
  _globals['_GETHISTORYREQUEST']._serialized_start=212
  _globals['_GETHISTORYREQUEST']._serialized_end=249
  _globals['_GETHISTORYRESPONSE']._serialized_start=251
  _globals['_GETHISTORYRESPONSE']._serialized_end=312
  _globals['_CHATMESSAGE']._serialized_start=314
  _globals['_CHATMESSAGE']._serialized_end=377
  _globals['_OBSIDIANSERVICE']._serialized_start=380
  _globals['_OBSIDIANSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
